### ISSUE TITLE
 Implement OTP Verification and Password Reset Logic

### ISSUE THREAD

**Issue by hima890** [hima890/TechStore-Platform#14]
We need to implement the logic for verifying the OTP and allowing users to reset their passwords on our TechStore platform. The OTP is already being generated and sent via email. Now, we need to verify the OTP provided by the user and allow them to proceed with resetting their password.

### Tasks:
1. **OTP Verification Logic**:
   

- [x] - Implement a function to verify the OTP provided by the user.
- [x]    - Ensure that the OTP is valid (matches the stored OTP) and has not expired (10-minute validity).
- [x]    - If the OTP is valid, allow the user to proceed to the password reset form.
- [x]    - Return appropriate error messages if the OTP is invalid or expired (e.g., “Invalid OTP” or “OTP expired”).

2. **Password Reset Form**:
   

- [x] - Once the OTP is verified, provide the user with a form to input their new password.
- [x]    - Ensure the password follows security guidelines (e.g., minimum length, combination of characters).
- [x]    - Use secure methods to handle and hash the new password before storing it in the database.
- [ ] 

3. **Password Reset API**:
 

- [x]   - Create an API endpoint to handle the password reset request.
- [x]    - Validate the new password input by the user.
- [x]    - Once the password is valid, update the user's password in the database with a securely hashed version.
- [x]    - Provide confirmation to the user that the password has been successfully reset.

4. **Error Handling**:
   

- [x] - Ensure that the API returns appropriate error responses if the OTP is incorrect, expired, or if the password does not meet validation criteria.
- [x]    - Clear the OTP from the database after it has been successfully used or if it expires.

### Expected Flow:
- User submits the OTP for verification.
- If OTP is valid, the user is prompted to input a new password.
- The new password is validated and saved in the database, replacing the old password.
- The OTP is invalidated or removed after the password is successfully reset.

### Technical Details:
- OTP length: 6 digits
- OTP validity: 10 minutes
- Ensure secure handling of passwords (hashing before storage).
- OTP should be removed from the database once it has been successfully used or expired.

### API Endpoints:
- **POST** `/api/v1/otp-verify`: Verifies the OTP provided by the user.
- **POST** `/api/v1/password-reset`: Allows the user to reset their password after successful OTP verification.

---

### Example Request/Response for OTP Verification:

**POST** `/api/v1/otp-verify`
```json
{
  "email": "user@example.com",
  "otp": "123456"
}
```

_Response_:
```json
{
  "message": "OTP verified successfully. Please proceed to reset your password."
}
```

---

### Example Request/Response for Password Reset:

**POST** `/api/v1/password-reset`
```json
{
  "email": "user@example.com",
  "new_password": "NewPassword123"
}
```

_Response_:
```json
{
  "message": "Password has been reset successfully."
}
```

---

### Additional Notes:
- Ensure secure communication (use HTTPS).
- Use proper password hashing (e.g., bcrypt).
- Implement appropriate error messages for invalid OTPs and invalid password inputs.
