### ISSUE TITLE
Create GET Endpoint to Retrieve All Stores with Product Information

### ISSUE THREAD

**Issue by hima890** [hima890/TechStore-Platform#24]
We need to implement an endpoint that handles a GET request and returns all the stores registered on the platform. This endpoint should return detailed store information, as well as the associated products of each store.

### **Endpoint Requirements:**

- **HTTP Method:** `GET`
- **Route:** `/stores` (or `/api/stores` depending on the route structure)
- **Response:** 
  - A list of all stores with the following details:
    - **Store Information:**
      - `id`: Store ID
      - `owner`: Store owner name or ID
      - `phone_number`: Contact number for the store
      - `email`: Contact email for the store
      - `social_media_link`: Any associated social media links for the store
      - `store_name`: The name of the store
      - `bio`: A brief description or bio of the store
      - `cover_image`: URL for the cover image of the store
      - `profile_image`: URL for the profile image of the store
    - **Store Products (if any):**
      - `id`: Product ID
      - `name`: Product name
      - `brand`: Product brand
      - `category`: Product category
      - `price`: Product price
      - `description`: Product description
      - `delivery`: Delivery options available for the product
      - `image_1`, `image_2`, `image_3`, `image_4`: URLs of the product images

### **Success Response:**

- **Status Code:** `200 OK`
- **Response Body Example:**
  ```json
  {
    "status": "success",
    "data": [
      {
        "id": 1,
        "owner": "John Doe",
        "phone_number": "+1234567890",
        "email": "john@example.com",
        "social_media_link": "http://instagram.com/store123",
        "store_name": "Tech Gadgets",
        "bio": "We sell the latest gadgets and tech accessories.",
        "cover_image": "http://example.com/cover.jpg",
        "profile_image": "http://example.com/profile.jpg",
        "products": [
          {
            "id": 101,
            "name": "Smartphone",
            "brand": "BrandX",
            "category": "Electronics",
            "price": "299.99",
            "description": "A high-end smartphone with great features.",
            "delivery": "Available",
            "image_1": "http://example.com/product1_image1.jpg",
            "image_2": "http://example.com/product1_image2.jpg",
            "image_3": null,
            "image_4": null
          },
          {
            "id": 102,
            "name": "Wireless Earbuds",
            "brand": "BrandY",
            "category": "Accessories",
            "price": "59.99",
            "description": "Noise-cancelling wireless earbuds.",
            "delivery": "Available",
            "image_1": "http://example.com/product2_image1.jpg",
            "image_2": null,
            "image_3": null,
            "image_4": null
          }
        ]
      }
    ]
  }
  ```

### **Error Response:**

- **Status Code:** `500 Internal Server Error`
- **Response Body Example:**
  ```json
  {
    "status": "error",
    "message": "Failed to retrieve stores data"
  }
  ```

### **Additional Notes:**

- The endpoint should handle scenarios where a store might not have any products yet.
- Ensure that the endpoint is paginated if there are many stores to prevent performance issues.
- Validate and sanitize the input if there are any query parameters or filters (e.g., search, category filters).
  
### **Tasks:**
- [x] Define the endpoint route and method.
- [x] Fetch all stores from the database along with their products.
- [x] Structure the response according to the given format.
- [x] Add error handling for potential failures during data retrieval.
- [x] Write unit tests to verify the correct functionality of the endpoint.
- [x] Add documentation for the new endpoint (e.g., Swagger or Postman collection).
