### ISSUE TITLE
Create Endpoint for Order Submission

### ISSUE THREAD

**Issue by hima890** [hima890/TechStore-Platform#30]
We need to create an API endpoint for submitting order information. This endpoint will allow users to send an order with the following fields:

- **Order Name**: The name of the order.
- **Email**: The email address of the customer.
- **Image**: The product image.
- **Title**: The title of the product being ordered.
- **Brand**: The brand associated with the product.
- **Description**: A brief description of the product.
- **Price**: The price of the product.
- **Quantity**: The number of items ordered.
- **Total**: The total amount for the order (calculated as `price * quantity`).

#### Task List:
- [ ] Create the order submission endpoint (`POST /orders`).
- [ ] Validate required fields (name, email, title, brand, price, quantity).
- [ ] Validate the format of the email.
- [ ] Handle file upload for the image.
- [ ] Add data validation to ensure valid price and quantity (e.g., no negative values).
- [ ] Automatically calculate the `total` field based on price and quantity.
- [ ] Return success or error response based on order processing.

#### Expected Response:
- **201 Created**: When the order is successfully processed.
- **400 Bad Request**: If any required fields are missing or invalid.
- **500 Internal Server Error**: If there is an issue with the server.

#### Additional Notes:
- Ensure that the image field supports file uploads (`multipart/form-data`).
- Consider implementing error handling for missing fields or invalid input.
- The endpoint should be secured with authentication (e.g., Bearer token).

#### Example Request:
```json
{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "img": "file.jpg",
  "title": "Smartphone",
  "brand": "TechBrand",
  "description": "Latest model of TechBrand's smartphone.",
  "price": 599.99,
  "quantity": 2,
  "total": 1199.98
}
```

#### Example Response:
```json
{
  "status": "success",
  "message": "Order created successfully!",
  "data": {
    "order_id": 123,
    "name": "John Doe",
    "email": "johndoe@example.com",
    "title": "Smartphone",
    "brand": "TechBrand",
    "price": 599.99,
    "quantity": 2,
    "total": 1199.98
  }
}
